### ISSUE TITLE
QRcode not generated - time out occurred on Manjaro 19.0.2

### ISSUE THREAD

**Issue by terpentin4code** [mayronceccon/send-message-whatsapp-line-command#1]
Hi, it seems that I am the first who responds to your project.

...let me say first: I look forward to using it and I will definitely give it a try on a different distro.

System details and messages:

send.py started in verbose mode
http://m.uploadedit.com/beth/1586962496557.txt

```
(.venv) 16:40:11-terpentin@Dreadnought:~/Downloads/send-message-whatsapp-line-command$ python send.py 
Traceback (most recent call last):
  File "send.py", line 20, in <module>
    qrcode = WebDriverWait(driver, 20).until(
  File "/home/terpentin/Downloads/send-message-whatsapp-line-command/.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

(.venv) 16:40:37-terpentin@Dreadnought:~/Downloads/send-message-whatsapp-line-command$ cat /etc/*rel*
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=19.0.2
DISTRIB_CODENAME=Kyria
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

(.venv) 16:41:36-terpentin@Dreadnought:~/Downloads/send-message-whatsapp-line-command$ ipacinfo python-virtualenv
Name            : python-virtualenv
Version         : 20.0.15-1
Description     : Virtual Python Environment builder
Architecture    : any
URL             : https://virtualenv.pypa.io/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python-setuptools  python-appdirs  python-filelock  python-six
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : virtualenv
Replaces        : virtualenv
Installed Size  : 4,86 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Sa 28 Mär 2020 02:46:35 CET
Install Date    : Mi 15 Apr 2020 16:37:37 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

(.venv) 16:43:06-terpentin@Dreadnought:~/Downloads/send-message-whatsapp-line-command$ ipacinfo python
Name            : python
Version         : 3.8.2-1
Description     : Next generation of the python high-level scripting language
Architecture    : x86_64
URL             : https://www.python.org/
Licenses        : custom
Groups          : None
Provides        : python3
Depends On      : expat  bzip2  gdbm  openssl  libffi  zlib  libnsl
Optional Deps   : python-setuptools [installed]
                  python-pip [installed]
                  sqlite [installed]
                  mpdecimal: for decimal
                  xz: for lzma [installed]
                  tk: for tkinter
Required By     : apparmor  bauh  bind-tools  ceph-libs  dynamic-wallpaper-editor  flatpak  glslang  glusterfs  gnome-layout-switcher  gnome-todo  gufw  libbytesize  libixion  libopenshot  libreoffice-still
                  libvirt-python  manjaro-application-utility  pacman-mirrors  pcsclite  python-appdirs  python-cairo  python-colorama  python-contextlib2  python-dbus  python-distlib  python-distro
                  python-docopt  python-evdev  python-filelock  python-gobject  python-idna  python-more-itertools  python-msgpack  python-npyscreen  python-ordered-set  python-pillow  python-ply
                  python-progress  python-pycups  python-pycurl  python-pyparsing  python-pyqt5-sip  python-pysmbc  python-pytoml  python-pyxdg  python-pyzmq  python-reportlab  python-setproctitle  python-sip
                  python-six  python-soupsieve  python-toml  python-urllib3  python-webencodings  python-wheel  python-yaml  python-zipp  smbclient  ufw  xfce4-screensaver
Optional For    : brltty  btrfs-progs  git  glib2  gupnp  ki18n  ldb  lensfun  libevent  libftdi  libieee1284  libnewt  libproxy  libpwquality  libvirt-glib  lilv  lirc  mlt  nfs-utils  nzbget-git  openexr
                  talloc  tdb  tevent  usbutils  util-linux  vim  vim-runtime  volume_key
Conflicts With  : None
Replaces        : python3
Installed Size  : 80,70 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mi 26 Feb 2020 23:21:03 CET
Install Date    : Mi 15 Apr 2020 16:37:02 CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

```

**Comment by mayronceccon** [comment]
Hi @terpentin4code! I'm happy to you use my project.

The problem was in loading the QRCODE, it was changed from img to canvas. I made the correction and updated the code.
